set_query:
  target:
    entity:
      integration: ha_mysql
      domain: sensor
  fields:
    query:
      required: false
      example: "SELECT name FROM emp WHERE id = %s"
      selector:
        text:
          multiline: true
    values:
      required: false
      example: "[1]"
      selector:
        object:

select_record:
  target:
    entity:
      integration: ha_mysql
      domain: sensor
  fields:
    rownumber:
      required: true
      example: 1
      selector:
        number:
          min: 0
          mode: box
